version: '3'

services:

  jupyterlab:
    image: jupyter/pyspark-notebook:spark-3.3.2
    container_name: jupyterlab
    restart: always
    ports:
      - '8888:8888'
      - '4041:4040'
    volumes:
      - ./data:/data
      - ./src:/src
      - ./work:/home/jovyan/work

  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src

  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKER_CORES=2
